name: test_curso
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
#   path: ^1.8.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
